package distributedSystem.DCMSCorba;


/**
* distributedSystem/DCMSCorba/DCMSInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from java.idl
* Wednesday, 4 August, 2021 7:57:16 PM EDT
*/

public abstract class DCMSInterfacePOA extends org.omg.PortableServer.Servant
 implements distributedSystem.DCMSCorba.DCMSInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createTRecord", new java.lang.Integer (0));
    _methods.put ("createSRecord", new java.lang.Integer (1));
    _methods.put ("getRecordCounts", new java.lang.Integer (2));
    _methods.put ("editRecord", new java.lang.Integer (3));
    _methods.put ("transferRecord", new java.lang.Integer (4));
    _methods.put ("listOfRecords", new java.lang.Integer (5));
    _methods.put ("getRecord", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // distributedSystem/DCMSCorba/DCMSInterface/createTRecord
       {
         String managerID = in.read_string ();
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phone = in.read_string ();
         String specialization = in.read_string ();
         String location = in.read_string ();
         String $result = null;
         $result = this.createTRecord (managerID, firstName, lastName, address, phone, specialization, location);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // distributedSystem/DCMSCorba/DCMSInterface/createSRecord
       {
         String managerID = in.read_string ();
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String courseRegistered = in.read_string ();
         String status = in.read_string ();
         String statusDate = in.read_string ();
         String $result = null;
         $result = this.createSRecord (managerID, firstName, lastName, courseRegistered, status, statusDate);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // distributedSystem/DCMSCorba/DCMSInterface/getRecordCounts
       {
         String $result = null;
         $result = this.getRecordCounts ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // distributedSystem/DCMSCorba/DCMSInterface/editRecord
       {
         String managerID = in.read_string ();
         String recordID = in.read_string ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         String $result = null;
         $result = this.editRecord (managerID, recordID, fieldName, newValue);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // distributedSystem/DCMSCorba/DCMSInterface/transferRecord
       {
         String managerID = in.read_string ();
         String recordID = in.read_string ();
         String remoteCenterServerName = in.read_string ();
         String $result = null;
         $result = this.transferRecord (managerID, recordID, remoteCenterServerName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // distributedSystem/DCMSCorba/DCMSInterface/listOfRecords
       {
         String $result = null;
         $result = this.listOfRecords ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // distributedSystem/DCMSCorba/DCMSInterface/getRecord
       {
         String recordID = in.read_string ();
         String $result = null;
         $result = this.getRecord (recordID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:distributedSystem/DCMSCorba/DCMSInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DCMSInterface _this() 
  {
    return DCMSInterfaceHelper.narrow(
    super._this_object());
  }

  public DCMSInterface _this(org.omg.CORBA.ORB orb) 
  {
    return DCMSInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class DCMSInterfacePOA
