package distributedSystem.DCMSCorba;


/**
* distributedSystem/DCMSCorba/DCMSInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from java.idl
* Wednesday, 4 August, 2021 7:57:16 PM EDT
*/

public interface DCMSInterface extends DCMSInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DCMSInterface
