package distributedSystem.DCMSCorba;


/**
* distributedSystem/DCMSCorba/DCMSInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from java.idl
* Wednesday, 4 August, 2021 7:57:16 PM EDT
*/

public interface DCMSInterfaceOperations 
{
  String createTRecord (String managerID, String firstName, String lastName, String address, String phone, String specialization, String location);
  String createSRecord (String managerID, String firstName, String lastName, String courseRegistered, String status, String statusDate);
  String getRecordCounts ();
  String editRecord (String managerID, String recordID, String fieldName, String newValue);
  String transferRecord (String managerID, String recordID, String remoteCenterServerName);
  String listOfRecords ();
  String getRecord (String recordID);
} // interface DCMSInterfaceOperations
