package distributedSystem.DCMSCorba;

/**
* distributedSystem/DCMSCorba/DCMSInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from java.idl
* Wednesday, 4 August, 2021 7:57:16 PM EDT
*/

public final class DCMSInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public distributedSystem.DCMSCorba.DCMSInterface value = null;

  public DCMSInterfaceHolder ()
  {
  }

  public DCMSInterfaceHolder (distributedSystem.DCMSCorba.DCMSInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = distributedSystem.DCMSCorba.DCMSInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    distributedSystem.DCMSCorba.DCMSInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return distributedSystem.DCMSCorba.DCMSInterfaceHelper.type ();
  }

}
